version: '3'

services:
  database:
    image: 'postgres:16'
    container_name: 'postgres'
    ports:
      - '5432:5432'
    environment:
      POSTGRES_USER: user
      POSTGRES_PASSWORD: password
      POSTGRES_DB: fittracker

  pgadmin:
    image: 'dpage/pgadmin4'
    container_name: 'pgadmin4'
    ports:
      - '5050:80'
    environment:
      PGADMIN_DEFAULT_EMAIL: user@example.com
      PGADMIN_DEFAULT_PASSWORD: password
