version: '3'

services:
  fittracker:
    image: 'fittracker:latest'
    container_name: 'fittracker'
    ports:
      - '8080:8080'
    environment:
      DB_HOST: postgres
    depends_on:
      - database
    profiles:
      - donotstart

  database:
    image: 'postgres:16'
    container_name: 'postgres'
    ports:
      - '5432:5432'
    environment:
      POSTGRES_USER: user
      POSTGRES_PASSWORD: password
      POSTGRES_DB: fittracker

  pgadmin:
    image: 'dpage/pgadmin4'
    container_name: 'pgadmin4'
    ports:
      - '5050:80'
    environment:
      PGADMIN_DEFAULT_EMAIL: user@example.com
      PGADMIN_DEFAULT_PASSWORD: password

  liquibase:
    image: 'liquibase/liquibase:4.23'
    container_name: 'liquibase'
    volumes:
      - ./database/changelog.yml:/liquibase/changelog.yml
      - ./src/test/resources:/liquibase/test-resources
      - ./database/scripts:/liquibase/scripts
      - ./database/liquibase.properties:/liquibase.properties
    depends_on:
      - database
    command:
      - '--defaults-file=/liquibase.properties'
      - '--contexts=default,dev'
      - 'update'
networks:
  default:
    name: fittracker