management:
    endpoints:
        web:
            base-path: /
            exposure.include: health
spring:
    datasource:
        url: jdbc:postgresql://localhost:5432/fittracker
        password: password
        username: user
    profiles:
        active: local

security:
    jwt:
        secret: "gHgQ0R2AbGjCwoy63dQKMCWyEhKzNwff1OHQteTTOh1EUgJJd09gLIscovYWLQf6eyr7IccpwpbvdXem"
        tokenExpirationPeriodMinutes: 60
---
spring:
    profiles:
        active: test
    liquibase:
        change-log: changelog.yml
    jwt:
        secret: "KpQ2DTrUzvqMSkWPG4VAiBkib432jL5MtxyHcqhr5f9rmGwV1XctLGjPxdtLGPDEXkPUYVN7xxzwYsld"
        tokenExpirationPeriodMinutes: 60
