management:
    endpoints:
        web:
            base-path: /
            exposure.include: health
spring:
    datasource:
        url: jdbc:postgresql://${DB_HOST:localhost}:5432/fittracker
        password: password
        username: user
---
spring:
    liquibase:
        change-log: changelog.yml
    config:
        activate:
            on-profile: test
